// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function EspFieldOrder() {
  return (
    <VizFigure caption={"RFC 4303 §2 기준 ESP 필드 배치. 파란 두 필드는 평문이지만 무결성 검증 범위에는 들어가고, 초록 네 필드가 암호화 범위(단 Payload Data 앞머리의 IV는 평문), 마지막 ICV가 앞의 전부를 검증한다."}>
      <Flowchart
        accessible="img"
        title={"ESP 패킷의 필드 순서 — SPI부터 ICV까지"}
        desc={"RFC 4303 §2 기준 ESP 필드 배치. 파란 두 필드는 평문이지만 무결성 검증 범위에는 들어가고, 초록 네 필드가 암호화 범위(단 Payload Data 앞머리의 IV는 평문), 마지막 ICV가 앞의 전부를 검증한다."}
        viewBox="0 0 600 468"
        data={{
  "nodes": [
    {
      "id": "spi",
      "x": 160,
      "y": 16,
      "width": 280,
      "height": 52,
      "label": "SPI · 4바이트 — 어느 SA로 풀까",
      "stroke": "#4E6CA8"
    },
    {
      "id": "seq",
      "x": 160,
      "y": 80,
      "width": 280,
      "height": 52,
      "label": "Sequence Number · 4바이트 — 재생 방지",
      "stroke": "#4E6CA8"
    },
    {
      "id": "pay",
      "x": 160,
      "y": 144,
      "width": 280,
      "height": 52,
      "label": "Payload Data · 가변 — IV(평문) + 암호문",
      "stroke": "#3E6B4F"
    },
    {
      "id": "pad",
      "x": 160,
      "y": 208,
      "width": 280,
      "height": 52,
      "label": "Padding · 0~255바이트",
      "stroke": "#3E6B4F"
    },
    {
      "id": "plen",
      "x": 160,
      "y": 272,
      "width": 280,
      "height": 52,
      "label": "Pad Length · 1바이트",
      "stroke": "#3E6B4F"
    },
    {
      "id": "nh",
      "x": 160,
      "y": 336,
      "width": 280,
      "height": 52,
      "label": "Next Header · 1바이트 — 59면 더미",
      "stroke": "#3E6B4F"
    },
    {
      "id": "icv",
      "x": 160,
      "y": 400,
      "width": 280,
      "height": 52,
      "label": "ICV · 가변 — 협상된 길이만큼",
      "stroke": "#6B6B3E"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "spi",
      "to": "seq",
      "routing": "straight"
    },
    {
      "id": "e2",
      "from": "seq",
      "to": "pay",
      "routing": "straight"
    },
    {
      "id": "e3",
      "from": "pay",
      "to": "pad",
      "routing": "straight"
    },
    {
      "id": "e4",
      "from": "pad",
      "to": "plen",
      "routing": "straight"
    },
    {
      "id": "e5",
      "from": "plen",
      "to": "nh",
      "routing": "straight"
    },
    {
      "id": "e6",
      "from": "nh",
      "to": "icv",
      "routing": "straight"
    }
  ]
}}
      />
    </VizFigure>
  );
}
