// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { ProcessSteps } from "@centurio1987/bbangto-ui-visualization";

export default function MtuBlackhole() {
  return (
    <VizFigure caption={"각 단계는 개별적으로는 정상 동작이다. ICMP를 막는 한 걸음이 전체 되먹임 고리를 끊는다."}>
      <ProcessSteps
        accessible="img"
        title={"MTU 블랙홀이 만들어지는 다섯 단계"}
        desc={"각 단계는 개별적으로는 정상 동작이다. ICMP를 막는 한 걸음이 전체 되먹임 고리를 끊는다."}
        viewBox="0 0 600 380"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "1. 큰 패킷 송신",
      "description": "종단 스택이 인터페이스 MTU를 기준 삼아 DF 비트를 세운 큰 패킷을 보낸다"
    },
    {
      "title": "2. 터널에서 초과",
      "description": "ESP 오버헤드가 붙어 경로 MTU를 넘어선다"
    },
    {
      "title": "3. 라우터가 폐기",
      "description": "DF가 세워져 있어 조각내지 못하고 버린다 — 규격대로의 정상 동작"
    },
    {
      "title": "4. ICMP가 차단됨",
      "description": "라우터가 보낸 Fragmentation Needed 메시지를 중간 방화벽이 막는다"
    },
    {
      "title": "5. 영원한 재전송",
      "description": "송신자는 원인을 모른 채 같은 크기로 재전송한다. 작은 패킷만 통과해 '되는데 안 되는' 증상이 된다"
    }
  ]
}}
      />
    </VizFigure>
  );
}
