// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Comparison } from "@centurio1987/bbangto-ui-visualization";

export default function TransportVsTunnel() {
  return (
    <VizFigure caption={"차이는 원본 IP 헤더의 위치 하나다. tunnel은 그것까지 페이로드로 넣고 새 외부 헤더를 씌운다."}>
      <Comparison
        accessible="img"
        title={"ESP transport 모드와 tunnel 모드의 헤더 배치 비교"}
        desc={"차이는 원본 IP 헤더의 위치 하나다. tunnel은 그것까지 페이로드로 넣고 새 외부 헤더를 씌운다."}
        viewBox="0 0 600 218"
        mode="split"
        data={{
  "left": {
    "label": "Transport 모드",
    "items": [
      "IP → ESP → 데이터 → 트레일러",
      "원본 IP 헤더 그대로 노출",
      "출발지·목적지 주소가 평문",
      "종단 호스트끼리 직접 보호"
    ]
  },
  "right": {
    "label": "Tunnel 모드",
    "items": [
      "새 IP → ESP → 원본 IP → 데이터",
      "원본 IP 헤더까지 암호화",
      "내부 주소 체계가 숨겨짐",
      "게이트웨이 간 구간의 기본값"
    ]
  }
}}
      />
    </VizFigure>
  );
}
