// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import Comparison from "../../../lib/viz/Comparison";

export default function VizComparison3() {
  return (
    <VizFigure caption={"같은 \"안 보임\", 다른 안전성"}>
      <Comparison
        accessible="img"
        title={"COPY 후 RUN rm 방식과 secret mount 방식의 비교"}
        desc={"같은 \"안 보임\", 다른 안전성"}
        viewBox="0 0 600 180"
        mode="split"
        data={{
  "left": {
    "label": "❌ COPY 후 RUN rm",
    "items": [
      "컨테이너 안에서 안 보임",
      "레이어에서 복구 가능",
      "whiteout은 가릴 뿐"
    ]
  },
  "right": {
    "label": "✅ secret mount",
    "items": [
      "컨테이너 안에서 안 보임",
      "레이어에서 복구 불가",
      "애초에 레이어에 안 씀"
    ]
  }
}}
      />
    </VizFigure>
  );
}
