// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function VizFlowchart4() {
  return (
    <VizFigure caption={"한 장으로 다시 보는 릴레이 — 층마다 약속이 다르다"}>
      <Flowchart
        accessible="img"
        title={"docker CLI에서 커널까지 여섯 계층이 위에서 아래로 이어지는 구조도"}
        desc={"한 장으로 다시 보는 릴레이 — 층마다 약속이 다르다"}
        viewBox="0 0 600 500"
        data={{
  "nodes": [
    {
      "id": "cli",
      "x": 110,
      "y": 14,
      "width": 380,
      "height": 56,
      "label": "docker CLI — REST 요청을 던진다"
    },
    {
      "id": "dkr",
      "x": 110,
      "y": 110,
      "width": 380,
      "height": 56,
      "label": "dockerd — 요청을 받아 넘긴다"
    },
    {
      "id": "ctr",
      "x": 110,
      "y": 206,
      "width": 380,
      "height": 56,
      "label": "containerd — rootfs·설정을 차린다"
    },
    {
      "id": "shim",
      "x": 110,
      "y": 302,
      "width": 380,
      "height": 56,
      "label": "shim — ttRPC 수신 · 컨테이너를 품는다"
    },
    {
      "id": "runc",
      "x": 110,
      "y": 398,
      "width": 380,
      "height": 42,
      "label": "runc — 낳고 물러난다"
    },
    {
      "id": "krn",
      "x": 110,
      "y": 452,
      "width": 380,
      "height": 40,
      "label": "커널 — namespace · cgroup · overlayfs"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "cli",
      "to": "dkr",
      "routing": "straight"
    },
    {
      "id": "e2",
      "from": "dkr",
      "to": "ctr",
      "routing": "straight"
    },
    {
      "id": "e3",
      "from": "ctr",
      "to": "shim",
      "routing": "straight"
    },
    {
      "id": "e4",
      "from": "shim",
      "to": "runc",
      "routing": "straight"
    },
    {
      "id": "e5",
      "from": "runc",
      "to": "krn",
      "routing": "straight"
    }
  ]
}}
      />
    </VizFigure>
  );
}
