// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { ProcessSteps } from "@centurio1987/bbangto-ui-visualization";

export default function VizProcessSteps2() {
  return (
    <VizFigure caption={"컨테이너 하나가 뜨기까지 — 바통이 넘어가는 순서"}>
      <ProcessSteps
        accessible="img"
        title={"docker CLI에서 시작해 dockerd, containerd, shim, runc 순으로 이어지는 다섯 단계"}
        desc={"컨테이너 하나가 뜨기까지 — 바통이 넘어가는 순서"}
        viewBox="0 0 600 300"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "docker run",
      "description": "CLI가 REST 요청을 던진다"
    },
    {
      "title": "dockerd",
      "description": "요청을 받아 아래로 넘긴다"
    },
    {
      "title": "containerd",
      "description": "rootfs와 설정을 준비한다"
    },
    {
      "title": "shim",
      "description": "소켓을 열고 컨테이너를 품는다"
    },
    {
      "title": "runc",
      "description": "컨테이너를 낳고 물러난다"
    }
  ]
}}
      />
    </VizFigure>
  );
}
