/**
 * 토큰 게이트 예외 표 — **근거 문서의 위치가 필수 필드다** (KAN-070 S10).
 *
 * 왜 필수인가.
 *   감사가 판정 규칙으로 이걸 못 박았다 — "정당한 예외는 근거 문서의 위치를 걸 수 있을
 *   때만 그렇다. 근거가 없으면 위반으로 내린다. **근거 없이 '일부러 그런 것 같다'로
 *   넘기면 그게 곧 드리프트의 정착이다**"(`design-concept/UI_CONSISTENCY_AUDIT.md` §3-7).
 *   실제로 예외 후보 넷 중 셋이 근거를 못 걸어 위반으로 내려갔다.
 *
 *   규칙을 글로만 적어 두면 다음 사람이 예외를 하나 더 넣을 때 조용히 샌다. 그래서
 *   **게이트가 자기 예외 표를 먼저 검사한다** — 근거가 비었거나, 그 파일이 없거나,
 *   그 줄이 없으면 게이트가 **자기 자신을 비0 으로 끝낸다.** 예외를 늘리는 값이
 *   게이트를 무력화하는 값과 같아지지 않게 하는 장치다.
 *
 * 왜 한 파일인가.
 *   같은 예외가 세 곳에 흩어져 있었다 — `extract.ts` 의 스캔 제외, `color.ts` 의
 *   `EXCEPTIONS`, `docrule.ts` 의 `MOTION_CSS`. 셋이 같은 자리를 각자 적으면 하나만
 *   고쳐지는 날이 오고, 그날 게이트는 축마다 다른 말을 한다.
 *
 * 갈래는 둘이고 겹칠 수 있다.
 *   `scan`    스캔 대상에서 **표시**한다(빼지 않는다 — 감사 원자료와 히트 단위로
 *             대조하려면 추출 집합이 감사와 같아야 한다). 게이트 카운트에서만 뺀다.
 *   `verdict` 판정을 「정당한 예외」로 내린다.
 *   `motion.css` 는 둘 다다. `viz.css` 와 `apply-viz` 생성물은 `scan` 뿐이다 —
 *   감사가 `viz.css` 의 색 리터럴을 위반으로 남겨 뒀고, 그 판정을 여기서 뒤집지 않는다.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export interface TokenException {
  /** 사람이 부르는 이름. 게이트 출력과 베이스라인에 그대로 나간다. */
  id: string;
  kind: ("scan" | "verdict")[];
  /** 무엇을 예외로 두는가. */
  what: string;
  /** 왜. 한 줄. */
  why: string;
  /**
   * **근거 문서의 위치. 비울 수 없다.** `경로:줄` 꼴이고 그 줄이 실제로 있어야 한다.
   * 여러 개면 다 적는다 — 하나가 사라져도 나머지가 남는다.
   */
  evidence: string[];
  match(file: string, text: string): boolean;
  /**
   * **자리 단위 좁히기(선택).** 있으면 `match` 로 고른 파일 **안에서 이 술어를 만족하는
   * 히트만** 예외가 된다.
   *
   * 왜 필요한가. `match` 는 파일 단위라 「이 파일의 이 값 하나만 일부러 그렇다」를 못 적는다.
   * 그래서 예외를 걸면 **그 파일의 준수분과 다른 부채까지 판정에서 통째로 내려간다** —
   * KAN-072 가 구분 팔레트 11건을 예외로 안 올린 이유가 정확히 이것이었다
   * (`KANBAN.cards/KAN-072-CPJCT1.md` 배치5 S2 보강). 값 하나를 지키려고 파일 전체의
   * 눈을 감기지 않는다.
   *
   * **줄 번호로 안 쓴다.** 같은 파일을 한 줄만 고쳐도 조용히 빗나가고, 빗나간 예외는
   * 「부채가 늘었다」가 아니라 「예외가 안 걸린다」로 나타나 원인을 짚기 어렵다.
   * 속성과 값으로 쓴다 — 편집에 안 흔들리고 무엇을 예외로 뒀는지가 그대로 읽힌다.
   */
  site?(hit: { prop: string; value: string; axis: string }): boolean;
}

export const EXCEPTIONS: TokenException[] = [
  {
    id: "motion-css-generated",
    kind: ["scan", "verdict"],
    what: "src/styles/motion.css 전체",
    why: "생성물 — scripts/gen-motion-css.ts 가 bbangtoTonyFoundation 에서 굽는다. 정본이 TS 라 방향이 반대다",
    evidence: ["src/styles/motion.css:2", ".github/workflows/main.yml:57"],
    match: (f) => f === "src/styles/motion.css",
  },
  {
    id: "viz-css-vendored",
    kind: ["scan"],
    what: "src/styles/viz.css 전체",
    why: "패키지 복제물 — @centurio1987/bbangto-ui-visualization 의 CONTRACT_CSS 사본이라 고쳐도 재추출에서 되돌아간다",
    evidence: ["src/styles/viz.css:4"],
    match: (f) => f === "src/styles/viz.css",
  },
  {
    id: "accent-bar-5px",
    kind: ["verdict"],
    what: "글 안 시뮬 네 곳의 borderLeft 5px 왼쪽 강조 막대",
    why: "굵기가 곧 뜻인 자리 — 옆 테두리가 --stroke-hair(1px) 이라 5배로 단을 가르는데, --stroke-bold(2px) 로 밀면 배율이 2배로 떨어져 막대와 테두리가 한 단으로 붙는다",
    evidence: ["design-concept/DESIGN_CONCEPT.md:369"],
    match: (f) => [
      "src/components/posts/osi-7-layers-2/FrameAnatomy.tsx",
      "src/components/posts/osi-7-layers-3/RoutingTableLab.tsx",
      "src/components/posts/osi-7-layers-6/DnsResolveLab.tsx",
      "src/components/posts/osi-7-layers-6/RequestJourneyLab.tsx",
    ].includes(f),
    // 자리 단위 — 그 파일의 다른 값은 계속 판정한다. 줄 번호를 안 쓰는 이유는 위 주석에.
    site: (h) => h.prop === "borderLeft" && h.value === "5px",
  },
  {
    id: "kraft-toggle-set",
    kind: ["verdict"],
    what: "vpn-anatomy-7/SplitTunnelLab.tsx 활성 토글의 크래프트 네 색",
    why: "넷이 서로를 받치는 한 벌이라 하나만 옮기면 짝이 깨지는데 토큰에 그 계열이 없다 — 최근접이 --cat-quality Δ42 · --fate-leak-bg Δ16 으로 전부 역할이 다르다",
    evidence: ["design-concept/DESIGN_CONCEPT.md:95"],
    match: (f) => f === "src/components/posts/vpn-anatomy-7/SplitTunnelLab.tsx",
    site: (h) => ["#8a7a56", "#efe3c6", "#4a3f26", "#7a7264"].includes(h.value),
  },
  {
    id: "doodle-crayon-stroke",
    kind: ["verdict"],
    what: "Doodle.astro 의 강조 두들(속도선·별표) stroke-width 3.2",
    why: "배율 1 로 굳은 SVG 라 판정에는 들어오지만 UI 테두리가 아니라 크레용 획이다 — 나란히 서는 두 그림의 필압이 갈리고, --deco-ink-fine 필터를 지난 뒤의 굵기라 3단과 같은 자가 아니다",
    evidence: ["design-concept/DESIGN_CONCEPT.md:402"],
    match: (f) => f === "src/components/deco/Doodle.astro",
    // 자리 단위 — 이 파일의 나머지 49 자리(전부 사용자 단위)와 색 준수분은 그대로 판정한다.
    site: (h) => h.axis === "stroke" && h.value === "3.2px",
  },
  {
    id: "apply-viz-generated",
    kind: ["scan"],
    what: "AUTO-GENERATED 헤더가 붙은 apply-viz 산출물",
    why: "생성물 — 좌표를 건드리면 다이어그램 기하가 깨지고 빌드·타입은 초록이다",
    evidence: ["scripts/apply-viz.ts:87"],
    match: (_f, t) => t.includes("AUTO-GENERATED by scripts/apply-viz.ts"),
  },
];

const LOC = /^(.+):(\d+)$/;

/**
 * 예외 표 자기 검사. 게이트가 **다른 무엇보다 먼저** 부른다.
 * 돌려주는 문자열이 하나라도 있으면 그것이 곧 게이트 실패 사유다.
 */
export function validateExceptions(root: string): string[] {
  const bad: string[] = [];
  const seen = new Set<string>();
  for (const e of EXCEPTIONS) {
    if (seen.has(e.id)) bad.push(`예외 id 가 겹친다: ${e.id}`);
    seen.add(e.id);
    if (!e.kind.length) bad.push(`예외 「${e.id}」 에 갈래가 없다(scan·verdict 중 하나는 있어야 한다)`);
    if (!e.why.trim()) bad.push(`예외 「${e.id}」 에 사유가 비었다`);
    if (e.site && !e.kind.includes("verdict")) {
      bad.push(`예외 「${e.id}」 에 site 가 있는데 갈래에 verdict 가 없다 — 자리 단위 좁히기는 판정 예외에만 뜻이 있다`);
    }
    if (!e.evidence.length) {
      bad.push(`예외 「${e.id}」 에 근거 문서 위치가 없다 — 근거 없는 예외는 안 받는다`);
      continue;
    }
    for (const ev of e.evidence) {
      const m = LOC.exec(ev);
      if (!m) { bad.push(`예외 「${e.id}」 의 근거 「${ev}」 가 경로:줄 꼴이 아니다`); continue; }
      const [, path, lineStr] = m;
      const abs = join(root, path);
      if (!existsSync(abs)) { bad.push(`예외 「${e.id}」 의 근거 파일이 없다 — ${path}`); continue; }
      const lines = readFileSync(abs, "utf-8").split("\n").length;
      const n = Number(lineStr);
      if (n < 1 || n > lines) bad.push(`예외 「${e.id}」 의 근거 「${ev}」 — 그 파일은 ${lines}줄뿐이다`);
    }
  }
  return bad;
}

export const scanExceptionFor = (file: string, text: string): TokenException | null =>
  EXCEPTIONS.find((e) => e.kind.includes("scan") && e.match(file, text)) ?? null;

export const verdictExceptionFor = (
  file: string, text = "", hit?: { prop: string; value: string; axis: string },
): TokenException | null =>
  EXCEPTIONS.find((e) =>
    e.kind.includes("verdict") && e.match(file, text) && (!e.site || (hit ? e.site(hit) : false)),
  ) ?? null;
