// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function CryptokeyRoutingFlow() {
  return (
    <VizFigure caption={"같은 표가 나가는 방향에서는 라우팅을, 들어오는 방향에서는 소스 IP 인증을 맡는다. 왼쪽이 송신, 오른쪽이 수신 경로다."}>
      <Flowchart
        accessible="img"
        title={"같은 표가 나가는 방향에서는 라우팅을, 들어오는 방향에서는 소스 IP 인증을 맡는다. 왼쪽이 송신, 오른쪽이 수신 경로다."}
        desc={"같은 표가 나가는 방향에서는 라우팅을, 들어오는 방향에서는 소스 IP 인증을 맡는다. 왼쪽이 송신, 오른쪽이 수신 경로다."}
        viewBox="0 0 640 300"
        data={{
  "nodes": [
    {
      "id": "out",
      "x": 24,
      "y": 24,
      "width": 260,
      "height": 48,
      "label": "나가는 패킷: 목적지 IP",
      "stroke": "#4E6CA8"
    },
    {
      "id": "lookup",
      "x": 24,
      "y": 108,
      "width": 260,
      "height": 48,
      "label": "표 조회 (longest-prefix)",
      "stroke": "#4E6CA8"
    },
    {
      "id": "enc",
      "x": 24,
      "y": 192,
      "width": 260,
      "height": 48,
      "label": "매칭된 피어의 공개키로 암호화",
      "stroke": "#3E6B4F"
    },
    {
      "id": "in",
      "x": 356,
      "y": 24,
      "width": 260,
      "height": 48,
      "label": "들어오는 패킷: 세션 키로 복호",
      "stroke": "#4E6CA8"
    },
    {
      "id": "which",
      "x": 356,
      "y": 108,
      "width": 260,
      "height": 48,
      "label": "복호에 쓰인 키 = 어느 피어인가",
      "stroke": "#4E6CA8"
    },
    {
      "id": "check",
      "x": 356,
      "y": 192,
      "width": 260,
      "height": 48,
      "label": "소스 IP가 그 피어 Allowed IP인가",
      "stroke": "#6B6B3E"
    }
  ],
  "edges": [
    {
      "id": "o1",
      "from": "out",
      "to": "lookup",
      "routing": "straight"
    },
    {
      "id": "o2",
      "from": "lookup",
      "to": "enc",
      "routing": "straight"
    },
    {
      "id": "i1",
      "from": "in",
      "to": "which",
      "routing": "straight"
    },
    {
      "id": "i2",
      "from": "which",
      "to": "check",
      "routing": "straight"
    }
  ]
}}
      />
    </VizFigure>
  );
}
