// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import ProcessSteps from "../../../lib/viz/ProcessSteps";

export default function OneRttFlow() {
  return (
    <VizFigure caption={"정상 흐름은 Initiation → Response로 한 번의 왕복(1-RTT)에 끝나고, 그 뒤로는 Transport Data만 오간다."}>
      <ProcessSteps
        accessible="img"
        title={"정상 흐름은 Initiation → Response로 한 번의 왕복(1-RTT)에 끝나고, 그 뒤로는 Transport Data만 오간다."}
        desc={"정상 흐름은 Initiation → Response로 한 번의 왕복(1-RTT)에 끝나고, 그 뒤로는 Transport Data만 오간다."}
        viewBox="0 0 600 360"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "1. Handshake Initiation (type 1, 148B)",
      "description": "개시자 → 응답자. 임시 키·암호화된 정적 키·타임스탬프를 싣는다"
    },
    {
      "title": "2. Handshake Response (type 2, 92B)",
      "description": "응답자 → 개시자. 이 한 번의 왕복으로 양쪽이 세션 키를 얻는다 (1-RTT)"
    },
    {
      "title": "3. Transport Data (type 4, 가변)",
      "description": "이후 실제 데이터. 16바이트 헤더 + AEAD 암호문"
    },
    {
      "title": "(부하 시) Cookie Reply (type 3, 64B)",
      "description": "DoS 방어. 정상 흐름에는 나타나지 않는다 — 이번 캡처에도 없다"
    }
  ]
}}
      />
    </VizFigure>
  );
}
