// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Comparison } from "@centurio1987/bbangto-ui-visualization";

export default function WgVsIpsec() {
  return (
    <VizFigure caption={"코드 규모를 두고 'WireGuard가 훨씬 작다'는 정성적 평가는 널리 인정되지만, 벤더 중립의 정량 수치는 이 글의 근거 범위 밖이라 숫자로는 적지 않는다."}>
      <Comparison
        accessible="img"
        title={"코드 규모를 두고 'WireGuard가 훨씬 작다'는 정성적 평가는 널리 인정되지만, 벤더 중립의 정량 수치는 이 글의 근거 범위 밖이라 숫자로는 적지 않는다."}
        desc={"코드 규모를 두고 'WireGuard가 훨씬 작다'는 정성적 평가는 널리 인정되지만, 벤더 중립의 정량 수치는 이 글의 근거 범위 밖이라 숫자로는 적지 않는다."}
        viewBox="0 0 640 360"
        data={{
  "left": {
    "label": "IPsec (IKEv2 + ESP)",
    "items": [
      "암호군을 SA/Proposal/Transform으로 협상",
      "신원·정책·SA를 IKEv2·SPD·SAD로 분리",
      "NAT 감지 시 UDP 500 → 4500 전환",
      "rekey는 CREATE_CHILD_SA 정책 기반",
      "메시지 길이 가변",
      "부품이 많아 유연하나 설정면이 넓다"
    ]
  },
  "right": {
    "label": "WireGuard",
    "items": [
      "협상 없음 — Noise_IKpsk2로 고정",
      "신원·라우팅·키를 Cryptokey Routing 표 하나로",
      "언제나 단일 UDP 포트 (로밍은 엔드포인트 자동 갱신)",
      "rekey는 120초 타이머로 자동",
      "핸드셰이크 148·92로 고정",
      "선택지가 좁아 예측 가능하고 공격면이 작다"
    ]
  }
}}
      />
    </VizFigure>
  );
}
