// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Comparison } from "@centurio1987/bbangto-ui-visualization";

export default function VizComparison3() {
  return (
    <VizFigure caption={"같은 이미지를 가리키는 두 방법"}>
      <Comparison
        accessible="img"
        title={"태그 참조와 다이제스트 참조의 차이 비교"}
        desc={"같은 이미지를 가리키는 두 방법"}
        viewBox="0 0 600 200"
        mode="split"
        data={{
  "left": {
    "label": "태그 nginx:1.25",
    "items": [
      "사람이 읽기 좋다",
      "가리키는 대상이 바뀔 수 있다",
      "매번 재확인이 필요하다"
    ]
  },
  "right": {
    "label": "다이제스트 @sha256:…",
    "items": [
      "읽기 어렵다",
      "대상이 절대 안 바뀐다",
      "받은 즉시 검증된다"
    ]
  }
}}
      />
    </VizFigure>
  );
}
