// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function VizFlowchart4() {
  return (
    <VizFigure caption={"이미지에서 실행까지 — Conversion 이 두 스펙을 잇는다"}>
      <Flowchart
        accessible="img"
        title={"Image Index에서 시작해 Conversion을 거쳐 번들과 런타임 연산으로 이어지는 흐름"}
        desc={"이미지에서 실행까지 — Conversion 이 두 스펙을 잇는다"}
        viewBox="0 0 600 500"
        data={{
  "nodes": [
    {
      "id": "idx",
      "x": 110,
      "y": 14,
      "width": 380,
      "height": 50,
      "label": "Image Index — 플랫폼을 고른다"
    },
    {
      "id": "man",
      "x": 110,
      "y": 100,
      "width": 380,
      "height": 50,
      "label": "Image Manifest — Descriptor 들"
    },
    {
      "id": "cfg",
      "x": 110,
      "y": 186,
      "width": 380,
      "height": 50,
      "label": "Config + Layers (blobs)"
    },
    {
      "id": "conv",
      "x": 110,
      "y": 272,
      "width": 380,
      "height": 56,
      "label": "Conversion — 풀어서 rootfs, 설정은 process 로"
    },
    {
      "id": "bun",
      "x": 110,
      "y": 364,
      "width": 380,
      "height": 50,
      "label": "번들 — config.json + rootfs/"
    },
    {
      "id": "run",
      "x": 110,
      "y": 450,
      "width": 380,
      "height": 40,
      "label": "create → start → running"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "idx",
      "to": "man",
      "routing": "straight"
    },
    {
      "id": "e2",
      "from": "man",
      "to": "cfg",
      "routing": "straight"
    },
    {
      "id": "e3",
      "from": "cfg",
      "to": "conv",
      "routing": "straight"
    },
    {
      "id": "e4",
      "from": "conv",
      "to": "bun",
      "routing": "straight"
    },
    {
      "id": "e5",
      "from": "bun",
      "to": "run",
      "routing": "straight"
    }
  ]
}}
      />
    </VizFigure>
  );
}
