// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import ProcessSteps from "../../../lib/viz/ProcessSteps";

export default function VizProcessSteps2() {
  return (
    <VizFigure caption={"런타임 스펙이 정한 다섯 연산 — 생성과 실행은 다른 사건이다"}>
      <ProcessSteps
        accessible="img"
        title={"create, start, running, kill, delete로 이어지는 컨테이너 생명주기"}
        desc={"런타임 스펙이 정한 다섯 연산 — 생성과 실행은 다른 사건이다"}
        viewBox="0 0 600 300"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "create",
      "description": "환경을 만든다. args 는 아직 실행 안 함"
    },
    {
      "title": "start",
      "description": "이제 args 를 실행한다"
    },
    {
      "title": "running",
      "description": "state 로 상태를 조회할 수 있다"
    },
    {
      "title": "kill",
      "description": "시그널을 보낸다"
    },
    {
      "title": "delete",
      "description": "create 가 만든 리소스를 거둔다"
    }
  ]
}}
      />
    </VizFigure>
  );
}
