// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import Comparison from "../../../lib/viz/Comparison";

export default function KernelVsUserspace() {
  return (
    <VizFigure caption={"성능 차이의 구조적 뿌리는 데이터 패스가 커널에 있느냐 유저스페이스에 있느냐다. 배수는 이 글에 없다 — 구조까지만 말한다."}>
      <Comparison
        accessible="img"
        title={"성능 차이의 구조적 뿌리는 데이터 패스가 커널에 있느냐 유저스페이스에 있느냐다. 배수는 이 글에 없다 — 구조까지만 말한다."}
        desc={"성능 차이의 구조적 뿌리는 데이터 패스가 커널에 있느냐 유저스페이스에 있느냐다. 배수는 이 글에 없다 — 구조까지만 말한다."}
        viewBox="0 0 620 260"
        mode="split"
        data={{
  "left": {
    "label": "커널 데이터 패스",
    "items": [
      "WireGuard: 처음부터 커널 모듈 설계",
      "OpenVPN 2.6 DCO: 데이터 채널만 커널로",
      "유저-커널 컨텍스트 스위치·복사 감소",
      "구조적 이점 — 정량 배수는 open question"
    ]
  },
  "right": {
    "label": "유저스페이스 데이터 패스",
    "items": [
      "OpenVPN 2.6 이전: 제어+데이터 모두 유저스페이스",
      "패킷마다 커널↔유저 왕복 비용",
      "유연성·이식성은 강점",
      "벤더중립 1차 벤치마크 미확보"
    ]
  }
}}
      />
    </VizFigure>
  );
}
