// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import ProcessSteps from "../../../lib/viz/ProcessSteps";

export default function MtuTriage() {
  return (
    <VizFigure caption={"MTU 블랙홀은 운영에서 발신자→경로 방향으로 거슬러 잡는다. 핵심은 ICMP가 돌아오는지다."}>
      <ProcessSteps
        accessible="img"
        title={"MTU 블랙홀은 운영에서 발신자→경로 방향으로 거슬러 잡는다. 핵심은 ICMP가 돌아오는지다."}
        desc={"MTU 블랙홀은 운영에서 발신자→경로 방향으로 거슬러 잡는다. 핵심은 ICMP가 돌아오는지다."}
        viewBox="0 0 480 520"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "1. 증상 인식",
      "description": "작은 요청은 되는데 큰 응답에서 멈춘다. ping은 되는데 대용량 전송·화면 공유가 죽는다"
    },
    {
      "title": "2. 경계 크기 찾기",
      "description": "DF 비트를 세운 ping으로 통과 크기와 실패 크기의 경계를 잡는다 — 그 경계가 곧 경로 MTU"
    },
    {
      "title": "3. ICMP 생존 확인",
      "description": "Fragmentation Needed(IPv6면 Packet Too Big)가 발신자에게 돌아오는지 본다 — 진단의 갈림길"
    },
    {
      "title": "4. 범인 지목",
      "description": "돌아오면 PMTUD 정상. 안 돌아오면 경로를 거슬러 어느 구간에서 사라지는지 좁힌다"
    },
    {
      "title": "5. 처방",
      "description": "방화벽에서 ICMP type 3 code 4 허용이 정석. 못 고치면 TCP는 MSS clamping, 큰 UDP는 남는다"
    }
  ]
}}
      />
    </VizFigure>
  );
}
