// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function VizSplitLeak() {
  return (
    <VizFigure caption={"split tunnel은 데이터를 두 경로로 가르지만, 이름 해석(DNS)은 별개로 결정된다 — 리졸버가 터널 밖이면 방문 도메인이 샌다."}>
      <Flowchart
        accessible="img"
        title={"split tunnel은 데이터를 두 경로로 가르지만, 이름 해석(DNS)은 별개로 결정된다 — 리졸버가 터널 밖이면 방문 도메인이 샌다."}
        desc={"split tunnel은 데이터를 두 경로로 가르지만, 이름 해석(DNS)은 별개로 결정된다 — 리졸버가 터널 밖이면 방문 도메인이 샌다."}
        viewBox="0 0 660 340"
        data={{
  "nodes": [
    {
      "id": "client",
      "x": 40,
      "y": 140,
      "width": 140,
      "height": 60,
      "label": "클라이언트"
    },
    {
      "id": "split",
      "x": 250,
      "y": 140,
      "width": 150,
      "height": 60,
      "label": "라우팅·리졸버 분기",
      "shape": "diamond"
    },
    {
      "id": "tunnel",
      "x": 470,
      "y": 40,
      "width": 150,
      "height": 56,
      "label": "암호화 터널 → 게이트웨이"
    },
    {
      "id": "direct",
      "x": 470,
      "y": 140,
      "width": 150,
      "height": 56,
      "label": "평문 직결 → ISP 관찰"
    },
    {
      "id": "dns",
      "x": 470,
      "y": 244,
      "width": 150,
      "height": 66,
      "label": "DNS 질의 노출 = 방문 도메인 유출",
      "fill": "#f4dcd4",
      "stroke": "#d99b86"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "client",
      "to": "split"
    },
    {
      "id": "e2",
      "from": "split",
      "to": "tunnel",
      "label": "보호 대상 대역"
    },
    {
      "id": "e3",
      "from": "split",
      "to": "direct",
      "label": "제외 대상"
    },
    {
      "id": "e4",
      "from": "split",
      "to": "dns",
      "label": "리졸버가 터널 밖",
      "dashed": true
    }
  ]
}}
      />
    </VizFigure>
  );
}
