// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Comparison } from "@centurio1987/bbangto-ui-visualization";

export default function VizComparison2() {
  return (
    <VizFigure caption={"같은 \"IP가 바뀐다\", 다른 적용 범위"}>
      <Comparison
        accessible="img"
        title={"프록시는 설정한 애플리케이션만, VPN은 인터페이스 전체를 덮는다"}
        desc={"같은 \"IP가 바뀐다\", 다른 적용 범위"}
        viewBox="0 0 600 210"
        mode="split"
        data={{
  "left": {
    "label": "프록시 (L7)",
    "items": [
      "설정한 앱만 경유",
      "다른 앱은 그냥 직접 나감",
      "트래픽을 그대로 전달",
      "암호화는 TLS의 몫"
    ]
  },
  "right": {
    "label": "VPN (L3)",
    "items": [
      "라우팅 테이블이 범위를 정함",
      "앱은 VPN을 몰라도 됨",
      "패킷을 통째로 감쌈",
      "암호화가 프로토콜에 내장"
    ]
  }
}}
      />
    </VizFigure>
  );
}
