// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import ProcessSteps from "../../../lib/viz/ProcessSteps";

export default function VizProcessSteps3() {
  return (
    <VizFigure caption={"캡슐화 — 원본 패킷은 payload가 되고, 겉에 새 헤더가 붙는다 (개념 레벨)"}>
      <ProcessSteps
        accessible="img"
        title={"원본 패킷이 암호화되어 새 외부 헤더로 감싸이고 게이트웨이에서 복원되는 네 단계"}
        desc={"캡슐화 — 원본 패킷은 payload가 되고, 겉에 새 헤더가 붙는다 (개념 레벨)"}
        viewBox="0 0 600 240"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "원본 패킷",
      "description": "목적지는 내가 쓰려는 서비스"
    },
    {
      "title": "잠그고 감싸기",
      "description": "패킷 전체가 암호화된 payload가 된다"
    },
    {
      "title": "새 외부 헤더",
      "description": "목적지는 VPN 게이트웨이"
    },
    {
      "title": "게이트웨이에서 복원",
      "description": "겉포장을 벗겨 원본을 내보낸다"
    }
  ]
}}
      />
    </VizFigure>
  );
}
