// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Comparison } from "@centurio1987/bbangto-ui-visualization";

export default function VizComparisonSpi() {
  return (
    <VizFigure caption={"IKE SPI는 협상 중이라 양쪽이 각자 하나씩(8+8), ESP SPI는 이미 선 SA를 받는 쪽이 고른 하나(4)"}>
      <Comparison
        accessible="img"
        title={"IKE SPI 8+8바이트 쌍과 ESP SPI 4바이트 하나의 대비"}
        desc={"IKE SPI는 협상 중이라 양쪽이 각자 하나씩(8+8), ESP SPI는 이미 선 SA를 받는 쪽이 고른 하나(4)"}
        viewBox="0 0 620 260"
        mode="split"
        data={{
  "left": {
    "label": "IKE SPI — 8 + 8바이트 한 쌍",
    "items": [
      "Initiator SPI 8B + Responder SPI 8B",
      "양쪽이 각자 하나씩 고른다",
      "협상 중이라 상대 SA가 아직 없다",
      "첫 요청엔 Responder SPI = 0"
    ]
  },
  "right": {
    "label": "ESP SPI — 4바이트 하나",
    "items": [
      "받는 쪽이 고른 32비트 값 하나",
      "이미 SA가 서 있다",
      "방향마다 하나씩 따로",
      "0은 예약 — NAT-T 때문에 못 쓴다(4편)"
    ]
  }
}}
      />
    </VizFigure>
  );
}
