// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import ProcessSteps from "../../../lib/viz/ProcessSteps";

export default function VizProcessStepsFourMessages() {
  return (
    <VizFigure caption={"IKE_SA_INIT 두 개로 공유 비밀을 세우고, IKE_AUTH 두 개로 서로를 인증하며 SA를 완성한다"}>
      <ProcessSteps
        accessible="img"
        title={"IKE_SA_INIT 요청·응답과 IKE_AUTH 요청·응답의 네 단계"}
        desc={"IKE_SA_INIT 두 개로 공유 비밀을 세우고, IKE_AUTH 두 개로 서로를 인증하며 SA를 완성한다"}
        viewBox="0 0 480 520"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "① IKE_SA_INIT 요청 · UDP 500",
      "description": "SA 제안 · KE(공개키) · Ni(nonce) — 전부 평문"
    },
    {
      "title": "② IKE_SA_INIT 응답 · UDP 500",
      "description": "SA 선택 · KEr · Nr — 여기서 공유 비밀 g^ir이 선다"
    },
    {
      "title": "③ IKE_AUTH 요청 · UDP 4500",
      "description": "SK{ IDi · AUTH · SA · TS } — 여기부터 암호문"
    },
    {
      "title": "④ IKE_AUTH 응답 · UDP 4500",
      "description": "SK{ IDr · AUTH · SA · TS } — IKE SA와 CHILD SA 완성"
    }
  ]
}}
      />
    </VizFigure>
  );
}
