// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Statistics } from "@centurio1987/bbangto-ui-visualization";

export default function BundleMemoryExample() {
  return (
    <VizFigure caption={"예시 측정 1건 — gethopp.app 벤치(2025-04, macOS, 단일 실행 N=1 면책). 최소 앱·창 6개 기준. 앱과 환경에 따라 달라지므로 대표 절대치가 아닙니다."}>
      <Statistics
        accessible="img"
        title={"Tauri와 Electron의 번들 크기와 메모리 사용량을 카드로 나열한 예시 수치"}
        desc={"예시 측정 1건 — gethopp.app 벤치(2025-04, macOS, 단일 실행 N=1 면책). 최소 앱·창 6개 기준. 앱과 환경에 따라 달라지므로 대표 절대치가 아닙니다."}
        viewBox="0 0 820 260"
        mode="cards"
        data={{
  "items": [
    {
      "label": "번들 · Tauri",
      "value": 8.6,
      "unit": "MB"
    },
    {
      "label": "번들 · Electron",
      "value": 244,
      "unit": "MB"
    },
    {
      "label": "메모리(창6) · Tauri",
      "value": 172,
      "unit": "MB"
    },
    {
      "label": "메모리(창6) · Electron",
      "value": 409,
      "unit": "MB"
    }
  ]
}}
      />
    </VizFigure>
  );
}
