// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import ProcessSteps from "../../../lib/viz/ProcessSteps";

export default function InvokeRoundTrip() {
  return (
    <VizFigure caption={"invoke() 왕복 — 프런트의 호출이 JSON으로 직렬화되어 Core를 거쳐 Rust 함수로, 다시 응답으로 돌아온다."}>
      <ProcessSteps
        accessible="img"
        title={"invoke() 왕복 — 프런트의 호출이 JSON으로 직렬화되어 Core를 거쳐 Rust 함수로, 다시 응답으로 돌아온다."}
        desc={"invoke() 왕복 — 프런트의 호출이 JSON으로 직렬화되어 Core를 거쳐 Rust 함수로, 다시 응답으로 돌아온다."}
        viewBox="0 0 560 460"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "① 프런트 invoke",
      "description": "invoke('greet', { message })"
    },
    {
      "title": "② Core 역직렬화",
      "description": "JSON 요청을 파싱해 커맨드 매칭"
    },
    {
      "title": "③ Rust 실행",
      "description": "#[tauri::command] 함수 호출"
    },
    {
      "title": "④ JSON 응답",
      "description": "반환값 직렬화 → Promise resolve"
    }
  ]
}}
      />
    </VizFigure>
  );
}
