// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Comparison } from "@centurio1987/bbangto-ui-visualization";

export default function TauriVsElectron() {
  return (
    <VizFigure caption={"같은 '웹 기술로 데스크톱 앱'이지만 렌더러·백엔드·보안 기본값이 구조적으로 다르다."}>
      <Comparison
        accessible="img"
        title={"Tauri와 Electron의 렌더러·백엔드·번들·보안·렌더링 일관성을 좌우로 비교한 표"}
        desc={"같은 '웹 기술로 데스크톱 앱'이지만 렌더러·백엔드·보안 기본값이 구조적으로 다르다."}
        viewBox="0 0 620 260"
        mode="split"
        data={{
  "left": {
    "label": "Tauri",
    "items": [
      "렌더러 = OS WebView (런타임 동적 링크)",
      "백엔드 = Rust 코어",
      "브라우저·JS 런타임 미번들",
      "기본 차단 + capabilities로 창별 허용",
      "OS별 WebView → 렌더링 차이 테스트 필요"
    ]
  },
  "right": {
    "label": "Electron",
    "items": [
      "렌더러 = Chromium 번들",
      "백엔드 = Node.js",
      "Chromium·Node 런타임 동봉",
      "nodeIntegration·contextIsolation 설정",
      "Chromium 고정 → 렌더링 일관"
    ]
  }
}}
      />
    </VizFigure>
  );
}
