// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function TauriRuntimeArchitecture() {
  return (
    <VizFigure caption={"Tauri 런타임: WebView(UI)는 오직 IPC 브리지를 통해서만 Rust Core에 요청하고, OS 자원에 대한 전권은 Core만 가진다."}>
      <Flowchart
        accessible="img"
        title={"WebView 프로세스에서 IPC 브리지를 거쳐 Rust Core 프로세스로, 다시 OS 자원으로 이어지는 세로 흐름도"}
        desc={"Tauri 런타임: WebView(UI)는 오직 IPC 브리지를 통해서만 Rust Core에 요청하고, OS 자원에 대한 전권은 Core만 가진다."}
        viewBox="0 0 580 558"
        data={{
  "nodes": [
    {
      "id": "webview",
      "x": 200,
      "y": 24,
      "width": 340,
      "height": 84,
      "label": "WebView 프로세스 — UI 렌더러 (HTML·CSS·JS, OS WebView)"
    },
    {
      "id": "ipc",
      "x": 200,
      "y": 168,
      "width": 340,
      "height": 74,
      "label": "IPC 브리지 — invoke · emit / listen",
      "fill": "var(--viz-accent-soft)"
    },
    {
      "id": "core",
      "x": 200,
      "y": 300,
      "width": 340,
      "height": 84,
      "label": "Rust Core 프로세스 — 창·트레이·전역 상태·IPC 라우팅"
    },
    {
      "id": "os",
      "x": 200,
      "y": 444,
      "width": 340,
      "height": 74,
      "label": "OS 자원 — 파일·네트워크·디바이스"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "webview",
      "to": "ipc",
      "label": "요청/구독"
    },
    {
      "id": "e2",
      "from": "ipc",
      "to": "core",
      "label": "커맨드 라우팅"
    },
    {
      "id": "e3",
      "from": "core",
      "to": "os",
      "label": "full access"
    }
  ]
}}
      />
    </VizFigure>
  );
}
