// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Comparison } from "@centurio1987/bbangto-ui-visualization";

export default function VizComparison4() {
  return (
    <VizFigure caption={"같은 작업, 다른 통로. 반환값은 끝나야 한 번 오지만 Channel은 진행 중에 순서대로 흐른다."}>
      <Comparison
        accessible="img"
        title={"커맨드 반환값 방식과 Channel 스트리밍 방식의 좌우 비교"}
        desc={"같은 작업, 다른 통로. 반환값은 끝나야 한 번 오지만 Channel은 진행 중에 순서대로 흐른다."}
        viewBox="0 0 620 250"
        mode="split"
        data={{
  "left": {
    "label": "커맨드 반환값 한 방",
    "items": [
      "응답은 작업이 끝난 뒤 1회",
      "진행 중 화면은 정지",
      "취소·중간 오류 노출 어려움",
      "결과가 크면 한꺼번에 직렬화"
    ]
  },
  "right": {
    "label": "Channel 스트리밍",
    "items": [
      "진행 중 여러 번 send",
      "순서 보장 · 제네릭 강타입",
      "부분 결과를 즉시 반영",
      "자식 프로세스 출력에 최적"
    ]
  }
}}
      />
    </VizFigure>
  );
}
