// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function VizFlowchart3() {
  return (
    <VizFigure caption={"커맨드 호출의 권한 심사 경로. 시스템 커맨드는 Runtime Authority에서 창별 케이퍼빌리티와 대조되고, 목록에 없으면 실행 전에 거절된다."}>
      <Flowchart
        accessible="img"
        title={"WebView의 invoke 호출이 Runtime Authority를 거쳐 케이퍼빌리티와 대조된 뒤 통과하거나 거절되는 흐름도"}
        desc={"커맨드 호출의 권한 심사 경로. 시스템 커맨드는 Runtime Authority에서 창별 케이퍼빌리티와 대조되고, 목록에 없으면 실행 전에 거절된다."}
        viewBox="0 0 620 452"
        data={{
  "nodes": [
    {
      "id": "call",
      "x": 20,
      "y": 14,
      "width": 320,
      "height": 62,
      "label": "WebView — invoke: open({ directory: true })"
    },
    {
      "id": "authority",
      "x": 20,
      "y": 136,
      "width": 320,
      "height": 62,
      "label": "Runtime Authority — 이 창이 쓸 자격이 있나",
      "fill": "#DCE4F2"
    },
    {
      "id": "cap",
      "x": 20,
      "y": 258,
      "width": 320,
      "height": 62,
      "label": "capabilities/default.json 대조"
    },
    {
      "id": "ok",
      "x": 20,
      "y": 380,
      "width": 320,
      "height": 62,
      "label": "허용 목록에 있음 → Rust 실행"
    },
    {
      "id": "deny",
      "x": 400,
      "y": 258,
      "width": 210,
      "height": 62,
      "label": "없음 → not allowed 거절",
      "fill": "#F0DEDE"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "call",
      "to": "authority",
      "label": "IPC",
      "routing": "straight"
    },
    {
      "id": "e2",
      "from": "authority",
      "to": "cap",
      "label": "permission 조회",
      "routing": "straight"
    },
    {
      "id": "e3",
      "from": "cap",
      "to": "ok",
      "label": "통과",
      "routing": "straight"
    },
    {
      "id": "e4",
      "from": "cap",
      "to": "deny",
      "label": "차단",
      "routing": "straight"
    }
  ]
}}
      />
    </VizFigure>
  );
}
