// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function VizFlowchart5() {
  return (
    <VizFigure caption={"완성된 file-scout의 배선. 프런트는 invoke로 요청만 보내고, 모든 OS 접촉과 외부 프로세스 실행은 Core 안에서 일어난다. 진행 상황은 Channel을 타고 역방향으로 흐른다."}>
      <Flowchart
        accessible="img"
        title={"WebView에서 invoke로 요청이 들어가 Rust Core가 파일 시스템과 사이드카를 다루고 Channel로 진행 상황을 되돌려 주는 구조도"}
        desc={"완성된 file-scout의 배선. 프런트는 invoke로 요청만 보내고, 모든 OS 접촉과 외부 프로세스 실행은 Core 안에서 일어난다. 진행 상황은 Channel을 타고 역방향으로 흐른다."}
        viewBox="0 0 640 486"
        data={{
  "nodes": [
    {
      "id": "ui",
      "x": 40,
      "y": 30,
      "width": 240,
      "height": 76,
      "label": "WebView — 폴더 선택 · 진행 표시"
    },
    {
      "id": "cmd",
      "x": 40,
      "y": 200,
      "width": 240,
      "height": 76,
      "label": "커맨드 scan_folder · checksum_file",
      "fill": "#DCE4F2"
    },
    {
      "id": "state",
      "x": 40,
      "y": 370,
      "width": 240,
      "height": 76,
      "label": "State — 최근 스캔 캐시"
    },
    {
      "id": "fs",
      "x": 380,
      "y": 200,
      "width": 220,
      "height": 76,
      "label": "OS 파일 시스템"
    },
    {
      "id": "side",
      "x": 380,
      "y": 370,
      "width": 220,
      "height": 76,
      "label": "사이드카 checksum CLI",
      "fill": "#EFE2C7"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "ui",
      "to": "cmd",
      "label": "invoke",
      "routing": "straight"
    },
    {
      "id": "e2",
      "from": "cmd",
      "to": "state",
      "label": "캐시 조회·갱신",
      "routing": "straight"
    },
    {
      "id": "e3",
      "from": "cmd",
      "to": "fs",
      "label": "read_dir"
    },
    {
      "id": "e4",
      "from": "cmd",
      "to": "side",
      "label": "spawn"
    },
    {
      "id": "e5",
      "from": "side",
      "to": "cmd",
      "label": "Stdout",
      "dashed": true
    },
    {
      "id": "e6",
      "from": "cmd",
      "to": "ui",
      "label": "Channel send",
      "dashed": true
    }
  ]
}}
      />
    </VizFigure>
  );
}
