// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function VizFlowchart5() {
  return (
    <VizFigure caption={"완성된 file-scout의 배선. 프런트는 invoke로 요청만 보내고, 모든 OS 접촉과 외부 프로세스 실행은 Core 안에서 일어난다. 진행 상황은 Channel을 타고 역방향으로 흐른다."}>
      <Flowchart
        accessible="img"
        title={"WebView에서 invoke로 요청이 들어가 Rust Core가 파일 시스템과 사이드카를 다루고 Channel로 진행 상황을 되돌려 주는 구조도"}
        desc={"완성된 file-scout의 배선. 프런트는 invoke로 요청만 보내고, 모든 OS 접촉과 외부 프로세스 실행은 Core 안에서 일어난다. 진행 상황은 Channel을 타고 역방향으로 흐른다."}
        viewBox="0 0 620 400"
        data={{
  "nodes": [
    {
      "id": "ui",
      "x": 160,
      "y": 14,
      "width": 300,
      "height": 60,
      "label": "WebView — 폴더 선택 · 진행 표시"
    },
    {
      "id": "ipc",
      "x": 160,
      "y": 112,
      "width": 300,
      "height": 50,
      "label": "IPC — invoke ↓ · Channel send ↑",
      "fill": "#DCE4F2"
    },
    {
      "id": "cmd",
      "x": 180,
      "y": 210,
      "width": 260,
      "height": 68,
      "label": "Rust 커맨드 scan_folder · checksum_file"
    },
    {
      "id": "fs",
      "x": 4,
      "y": 218,
      "width": 150,
      "height": 52,
      "label": "OS 파일 시스템 read_dir"
    },
    {
      "id": "side",
      "x": 466,
      "y": 218,
      "width": 150,
      "height": 52,
      "label": "사이드카 CLI spawn",
      "fill": "#EFE2C7"
    },
    {
      "id": "state",
      "x": 160,
      "y": 326,
      "width": 300,
      "height": 60,
      "label": "State — 최근 스캔 캐시"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "ui",
      "to": "ipc",
      "routing": "straight"
    },
    {
      "id": "e2",
      "from": "ipc",
      "to": "cmd",
      "routing": "straight"
    },
    {
      "id": "e3",
      "from": "cmd",
      "to": "fs",
      "routing": "straight"
    },
    {
      "id": "e4",
      "from": "cmd",
      "to": "side",
      "routing": "straight"
    },
    {
      "id": "e5",
      "from": "cmd",
      "to": "state",
      "routing": "straight"
    }
  ]
}}
      />
    </VizFigure>
  );
}
