// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { ProcessSteps } from "@centurio1987/bbangto-ui-visualization";

export default function VizProcessSteps2() {
  return (
    <VizFigure caption={"file-scout 구현 로드맵. 각 단계가 1편의 개념 하나를 코드로 바꾼다 — 뒤 단계는 앞 단계의 결과를 딛고 올라간다."}>
      <ProcessSteps
        accessible="img"
        title={"스캐폴딩부터 배포 빌드까지 여덟 단계로 이어지는 file-scout 구현 순서"}
        desc={"file-scout 구현 로드맵. 각 단계가 1편의 개념 하나를 코드로 바꾼다 — 뒤 단계는 앞 단계의 결과를 딛고 올라간다."}
        viewBox="0 0 520 900"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "0. 스캐폴딩",
      "description": "create-tauri-app · 어느 파일에 무엇이 있나"
    },
    {
      "title": "1. 첫 커맨드",
      "description": "#[tauri::command] ↔ invoke 왕복"
    },
    {
      "title": "2. 플러그인과 첫 거절",
      "description": "폴더 선택 dialog · 권한 에러 읽기"
    },
    {
      "title": "3. 권한 좁히기",
      "description": "capabilities JSON · scope 객체"
    },
    {
      "title": "4. 경계 설계",
      "description": "fs 플러그인이냐 내 커맨드냐"
    },
    {
      "title": "5. 상태",
      "description": "State · Mutex · async 함정"
    },
    {
      "title": "6. 진행률",
      "description": "반환값도 이벤트도 아닌 Channel"
    },
    {
      "title": "7. 사이드카",
      "description": "externalBin · target triple · 출력 중계"
    },
    {
      "title": "8. 배포 빌드",
      "description": "tauri build · 번들 타깃"
    }
  ]
}}
      />
    </VizFigure>
  );
}
