// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import Comparison from "../../../lib/viz/Comparison";

export default function VizComparison2() {
  return (
    <VizFigure caption={"한 줄 고르기가 아니라 층마다 한 칸씩"}>
      <Comparison
        accessible="img"
        title={"잘못된 선택 방식과 올바른 선택 방식의 비교"}
        desc={"한 줄 고르기가 아니라 층마다 한 칸씩"}
        viewBox="0 0 600 210"
        mode="split"
        data={{
  "left": {
    "label": "❌ 하나만 고르기",
    "items": [
      "\"도커 대신 Podman\"",
      "층 구분 없이 통째 교체",
      "바뀌는 범위를 모른다"
    ]
  },
  "right": {
    "label": "✅ 층마다 고르기",
    "items": [
      "노드는 containerd",
      "위험한 워크로드만 Kata",
      "빌드는 BuildKit"
    ]
  }
}}
      />
    </VizFigure>
  );
}
