// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function VizFlowchart3() {
  return (
    <VizFigure caption={"네 편이 쌓아 올린 지도 — 층마다 바꿀 수 있다"}>
      <Flowchart
        accessible="img"
        title={"빌드 도구부터 격리 모델까지 다섯 층과 각 층의 선택지"}
        desc={"네 편이 쌓아 올린 지도 — 층마다 바꿀 수 있다"}
        viewBox="0 0 600 420"
        data={{
  "nodes": [
    {
      "id": "build",
      "x": 100,
      "y": 14,
      "width": 400,
      "height": 50,
      "label": "빌드 — BuildKit · Buildah"
    },
    {
      "id": "engine",
      "x": 100,
      "y": 100,
      "width": 400,
      "height": 50,
      "label": "사람이 쓰는 엔진 — Docker · Podman"
    },
    {
      "id": "k8s",
      "x": 100,
      "y": 186,
      "width": 400,
      "height": 50,
      "label": "쿠버네티스 런타임 — containerd · CRI-O"
    },
    {
      "id": "rt",
      "x": 100,
      "y": 272,
      "width": 400,
      "height": 50,
      "label": "저수준 런타임 — runc · crun · youki"
    },
    {
      "id": "iso",
      "x": 100,
      "y": 358,
      "width": 400,
      "height": 48,
      "label": "격리 — namespace/cgroup · gVisor · Kata"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "build",
      "to": "engine",
      "routing": "straight"
    },
    {
      "id": "e2",
      "from": "engine",
      "to": "k8s",
      "routing": "straight"
    },
    {
      "id": "e3",
      "from": "k8s",
      "to": "rt",
      "routing": "straight"
    },
    {
      "id": "e4",
      "from": "rt",
      "to": "iso",
      "routing": "straight"
    }
  ]
}}
      />
    </VizFigure>
  );
}
