// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Comparison } from "@centurio1987/bbangto-ui-visualization";

export default function VizComparison3() {
  return (
    <VizFigure caption={"파라미터가 같으니 나머지 구조를 그대로 두고 갈아 끼울 수 있다"}>
      <Comparison
        accessible="img"
        title={"AES-GCM 계열과 ChaCha20-Poly1305의 파라미터 비교"}
        desc={"파라미터가 같으니 나머지 구조를 그대로 두고 갈아 끼울 수 있다"}
        viewBox="0 0 600 280"
        mode="split"
        data={{
  "left": {
    "label": "AEAD_AES_*_GCM",
    "items": [
      "키 16 또는 32 옥텟",
      "nonce 12 옥텟",
      "태그 16 옥텟",
      "AES 전용 명령이 있으면 유리"
    ]
  },
  "right": {
    "label": "AEAD_CHACHA20_POLY1305",
    "items": [
      "키 32 옥텟",
      "nonce 12 옥텟",
      "태그 16 옥텟",
      "전용 명령 없는 환경에서 유리"
    ]
  }
}}
      />
    </VizFigure>
  );
}
