// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function VizFlowchart4() {
  return (
    <VizFigure caption={"ChaCha20 블록함수가 Poly1305의 재료를 만든다 — 부트스트래핑 구조"}>
      <Flowchart
        accessible="img"
        title={"블록 카운터 0으로 호출한 ChaCha20 출력의 앞 256비트가 Poly1305 일회성 키가 되고, 그 키로 16바이트 태그를 만드는 흐름"}
        desc={"ChaCha20 블록함수가 Poly1305의 재료를 만든다 — 부트스트래핑 구조"}
        viewBox="0 0 600 390"
        data={{
  "nodes": [
    {
      "id": "n1",
      "x": 110,
      "y": 20,
      "width": 380,
      "height": 62,
      "label": "ChaCha20 블록함수 — 블록 카운터 = 0"
    },
    {
      "id": "n2",
      "x": 110,
      "y": 122,
      "width": 380,
      "height": 62,
      "label": "512비트 출력에서 앞 256비트만 취함"
    },
    {
      "id": "n3",
      "x": 110,
      "y": 224,
      "width": 380,
      "height": 62,
      "label": "Poly1305 일회성 키 — r(16B) + s(16B)"
    },
    {
      "id": "n4",
      "x": 110,
      "y": 306,
      "width": 380,
      "height": 62,
      "label": "Poly1305 → 16바이트 인증 태그"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "n1",
      "to": "n2",
      "routing": "straight"
    },
    {
      "id": "e2",
      "from": "n2",
      "to": "n3",
      "routing": "straight"
    },
    {
      "id": "e3",
      "from": "n3",
      "to": "n4",
      "routing": "straight"
    }
  ]
}}
      />
    </VizFigure>
  );
}
