// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { ProcessSteps } from "@centurio1987/bbangto-ui-visualization";

export default function VizProcessSteps2() {
  return (
    <VizFigure caption={"AEAD 암호화 파이프라인 — 입력 넷이 들어가 암호문과 태그 하나가 나온다"}>
      <ProcessSteps
        accessible="img"
        title={"K·N·P·A 입력에서 암호문과 인증 태그가 나오는 4단계 파이프라인"}
        desc={"AEAD 암호화 파이프라인 — 입력 넷이 들어가 암호문과 태그 하나가 나온다"}
        viewBox="0 0 600 420"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "입력 넷을 모은다",
      "description": "K(비밀 키) · N(nonce) · P(평문) · A(AAD)"
    },
    {
      "title": "P를 암호화한다",
      "description": "K와 N에서 얻은 키스트림으로 평문을 가린다"
    },
    {
      "title": "C와 A를 함께 인증한다",
      "description": "암호화된 본문과 평문 헤더를 하나의 태그로 묶는다"
    },
    {
      "title": "C를 내보낸다",
      "description": "암호문 뒤에 16바이트 인증 태그가 붙는다"
    }
  ]
}}
      />
    </VizFigure>
  );
}
