// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import Comparison from "../../../lib/viz/Comparison";

export default function VizComparison3() {
  return (
    <VizFigure caption={"둘 다 사전 공유 키를 쓰지만, tls-auth는 HMAC 서명만 얹어 핸드셰이크 겉면을 노출하고, tls-crypt는 제어 채널을 암호화해 그 겉면까지 숨긴다(TLS 1.3에선 인증서 자체는 이미 TLS가 암호화한다). 어느 쪽이든 맨 앞 opcode·세션 ID는 평문으로 남는다."}>
      <Comparison
        accessible="img"
        title={"tls-auth와 tls-crypt의 보호 범위 비교"}
        desc={"둘 다 사전 공유 키를 쓰지만, tls-auth는 HMAC 서명만 얹어 핸드셰이크 겉면을 노출하고, tls-crypt는 제어 채널을 암호화해 그 겉면까지 숨긴다(TLS 1.3에선 인증서 자체는 이미 TLS가 암호화한다). 어느 쪽이든 맨 앞 opcode·세션 ID는 평문으로 남는다."}
        viewBox="0 0 600 240"
        mode="split"
        data={{
  "left": {
    "label": "tls-auth — 서명",
    "items": [
      "제어 채널에 HMAC 서명만 덧붙임",
      "opcode·세션 ID 평문",
      "ClientHello·ServerHello 그대로 파싱됨",
      "인증서는 TLS가 이미 암호화(안 보임)"
    ]
  },
  "right": {
    "label": "tls-crypt — 암호화",
    "items": [
      "제어 페이로드를 AES-256-CTR로 암호화",
      "opcode·세션 ID는 여전히 평문",
      "핸드셰이크가 덩어리로만 보임",
      "핸드셰이크 존재까지 은닉 → DPI 회피"
    ]
  }
}}
      />
    </VizFigure>
  );
}
