// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function VizFlowchart2() {
  return (
    <VizFigure caption={"TLS 1.3 키 스케줄(RFC 8446 §7.1)의 요지. 각 시크릿은 이전 시크릿을 입력으로 한 단방향(HKDF) 출력이라, 뒤 단계가 유출돼도 앞 단계로 역산되지 않는다. 전진 비밀성 자체는 매 세션 임시 DH 키에서 나오고(2편 참고), 이 단방향 연쇄가 그 위에 얹힌다."}>
      <Flowchart
        accessible="img"
        title={"Early Secret에서 Handshake Secret, Master Secret으로 이어지는 단방향 HKDF 연쇄"}
        desc={"TLS 1.3 키 스케줄(RFC 8446 §7.1)의 요지. 각 시크릿은 이전 시크릿을 입력으로 한 단방향(HKDF) 출력이라, 뒤 단계가 유출돼도 앞 단계로 역산되지 않는다. 전진 비밀성 자체는 매 세션 임시 DH 키에서 나오고(2편 참고), 이 단방향 연쇄가 그 위에 얹힌다."}
        viewBox="0 0 560 320"
        data={{
  "nodes": [
    {
      "id": "e",
      "x": 140,
      "y": 16,
      "width": 280,
      "height": 56,
      "label": "Early Secret — HKDF-Extract(0, PSK)",
      "stroke": "#3E6B6B"
    },
    {
      "id": "h",
      "x": 140,
      "y": 132,
      "width": 280,
      "height": 56,
      "label": "Handshake Secret — 핸드셰이크 트래픽 키",
      "stroke": "#4E6CA8"
    },
    {
      "id": "m",
      "x": 140,
      "y": 248,
      "width": 280,
      "height": 56,
      "label": "Master Secret — 애플리케이션 트래픽 키",
      "stroke": "#3E6B4F"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "e",
      "to": "h",
      "routing": "straight"
    },
    {
      "id": "e2",
      "from": "h",
      "to": "m",
      "routing": "straight"
    }
  ]
}}
      />
    </VizFigure>
  );
}
