// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { ProcessSteps } from "@centurio1987/bbangto-ui-visualization";

export default function VizProcessSteps4() {
  return (
    <VizFigure caption={"OpenVPN을 TCP 모드로 쓰면, 터널링되는 앱의 내부 TCP와 OpenVPN 자신의 외부 TCP가 각자 재전송 타이머를 돌린다. 손실 하나가 두 계층에서 동시에 재전송을 촉발해 지연이 눈덩이처럼 불어난다."}>
      <ProcessSteps
        accessible="img"
        title={"TCP-over-TCP meltdown이 지연을 누적시키는 4단계"}
        desc={"OpenVPN을 TCP 모드로 쓰면, 터널링되는 앱의 내부 TCP와 OpenVPN 자신의 외부 TCP가 각자 재전송 타이머를 돌린다. 손실 하나가 두 계층에서 동시에 재전송을 촉발해 지연이 눈덩이처럼 불어난다."}
        viewBox="0 0 560 340"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "패킷 손실",
      "description": "경로에서 세그먼트 하나가 사라진다"
    },
    {
      "title": "내부 TCP 재전송",
      "description": "터널링되는 앱의 TCP가 재전송 타이머를 세운다"
    },
    {
      "title": "외부 TCP도 재전송",
      "description": "OpenVPN 자신의 TCP도 동시에 자기 재전송을 시도한다"
    },
    {
      "title": "지연 누적",
      "description": "두 계층의 재전송·혼잡제어가 겹쳐 지연이 눈덩이처럼 불어난다"
    }
  ]
}}
      />
    </VizFigure>
  );
}
