#!/usr/bin/env bun
/**
 * apply-viz — ```viz``` 블록 처리 엔진.
 *
 * MDX/draft 파일에서 ```viz``` 펜스드 블록(JSON)을 찾아:
 *  - target:"inline" → co-located React 컴포넌트(.tsx) 생성 + MDX import 삽입
 *                      + 블록을 <Name /> 로 치환 (client directive 없음 = SSR 정적 SVG)
 *  - target:"hero"   → 컴포넌트를 Playwright로 래스터해 public/images/<slug>/<name>.webp 생성
 *                      + 블록을 ![alt](경로) 로 치환   (hero 래스터는 render-viz.ts 위임)
 *
 * 규격: src/lib/viz/schema.ts (Zod, v1 5종). 스타일: src/lib/viz/blogVizStyleGuide.ts.
 * 렌더 색 바인딩: src/styles/viz.css(전역 shim).
 *
 * 사용:
 *   bun scripts/apply-viz.ts <mdx-file> [--slug <slug>] [--force] [--dry]
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { parseVizSpec, type VizSpec } from "../src/lib/viz/schema";
import { defaultViewBox, a11yText, extraProps } from "../src/lib/viz/layout";

const ROOT = process.cwd();

// ---------- args ----------
function parseArgs(argv: string[]) {
  const a = { file: "", slug: "", force: false, dry: false };
  for (let i = 2; i < argv.length; i++) {
    const t = argv[i];
    if (t === "--force") a.force = true;
    else if (t === "--dry") a.dry = true;
    else if (t === "--slug") a.slug = argv[++i] ?? "";
    else if (!a.file) a.file = t;
  }
  return a;
}

function slugFromFile(file: string) {
  return path
    .basename(file)
    .replace(/\.(md|mdx)$/, "")
    .replace(/-draft$/, "");
}

// ---------- name helpers ----------
function toPascal(s: string) {
  const cleaned = s.replace(/[^a-zA-Z0-9]+/g, " ").trim();
  const pascal = cleaned
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  const safe = /^[A-Za-z]/.test(pascal) ? pascal : `Viz${pascal}`;
  return safe || "VizFigure1";
}

// ---------- JSX prop helpers ----------
const str = (s: string) => JSON.stringify(s); // safe string literal
const jsonLiteral = (v: unknown) => JSON.stringify(v, null, 2);

/** kind별 top-level extra prop(layout.extraProps) 을 JSX 속성 문자열로. */
function extraPropsJsx(spec: VizSpec): string[] {
  return Object.entries(extraProps(spec)).map(([k, v]) =>
    v === true ? k : `${k}=${str(String(v))}`,
  );
}

/** inline 컴포넌트 소스 생성. */
function renderComponentSource(name: string, spec: VizSpec): string {
  const vb = defaultViewBox(spec);
  const { title, desc } = a11yText(spec);
  const extras = extraPropsJsx(spec).map((p) => `        ${p}`);
  const captionProp = spec.caption ? ` caption={${str(spec.caption)}}` : "";
  const body = [
    `        accessible="img"`,
    `        title={${str(title)}}`,
    `        desc={${str(desc)}}`,
    `        viewBox=${str(vb)}`,
    ...extras,
    `        data={${jsonLiteral(spec.data)}}`,
  ].join("\n");

  return `// AUTO-GENERATED by scripts/apply-viz.ts from a \`\`\`viz\`\`\` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { ${spec.kind} } from "@centurio1987/bbangto-ui-visualization";

export default function ${name}() {
  return (
    <VizFigure${captionProp}>
      <${spec.kind}
${body}
      />
    </VizFigure>
  );
}
`;
}

// ---------- MDX block regex ----------
const VIZ_BLOCK = /```viz\s*\n([\s\S]*?)\n```/g;

async function main() {
  const args = parseArgs(process.argv);
  if (!args.file) {
    console.error("usage: bun scripts/apply-viz.ts <mdx-file> [--slug <slug>] [--force] [--dry]");
    process.exit(1);
  }
  const filePath = path.resolve(ROOT, args.file);
  if (!existsSync(filePath)) {
    console.error(`file not found: ${filePath}`);
    process.exit(1);
  }
  const slug = args.slug || slugFromFile(args.file);
  const content = await readFile(filePath, "utf8");

  // frontmatter split
  const fmMatch = content.match(/^---\n[\s\S]*?\n---\n/);
  const frontmatter = fmMatch ? fmMatch[0] : "";
  let body = fmMatch ? content.slice(frontmatter.length) : content;

  const usedNames = new Set<string>();
  const newImports: string[] = [];
  const createdComponents: string[] = [];
  const heroCreated: string[] = [];
  const errors: string[] = [];
  let heroCount = 0;
  let index = 0;

  // collect matches first (regex is stateful)
  const matches = [...body.matchAll(VIZ_BLOCK)];
  if (matches.length === 0) {
    console.log(`[apply-viz] no \`\`\`viz\`\`\` blocks in ${args.file}`);
    return;
  }

  // process each block → build replacements
  const replacements: { from: string; to: string }[] = [];
  for (const m of matches) {
    index++;
    const label = `viz block #${index}`;
    let spec: VizSpec;
    try {
      const raw = JSON.parse(m[1]);
      spec = parseVizSpec(raw, label);
    } catch (e) {
      errors.push(`${label}: ${(e as Error).message}`);
      continue; // leave block in place
    }

    if (spec.target === "hero") {
      heroCount++;
      const heroName = toPascal(spec.name ?? "hero")
        .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
        .toLowerCase(); // "hero", "cover" 등 파일명 안전화
      const outRel = `public/images/${slug}/${heroName}.webp`;
      const { title } = a11yText(spec);
      const alt = spec.alt ?? spec.caption ?? title;
      const mdImg = `![${alt}](/images/${slug}/${heroName}.webp)`;
      if (args.dry) {
        heroCreated.push(`${outRel} [dry]`);
        replacements.push({ from: m[0], to: mdImg });
        continue;
      }
      try {
        const { rasterizeViz } = await import("./render-viz");
        await rasterizeViz(spec, path.join(ROOT, outRel), { force: args.force });
        heroCreated.push(outRel);
        replacements.push({ from: m[0], to: mdImg });
      } catch (e) {
        errors.push(`${label}: hero 래스터 실패 — ${(e as Error).message}. 블록 유지.`);
      }
      continue;
    }

    // inline: unique component name
    let name = toPascal(spec.name ?? `Viz${spec.kind}${index}`);
    let n = name;
    let dup = 2;
    while (usedNames.has(n)) n = `${name}${dup++}`;
    name = n;
    usedNames.add(name);

    const compDir = path.join(ROOT, "src", "components", "posts", slug);
    const compPath = path.join(compDir, `${name}.tsx`);
    if (existsSync(compPath) && !args.force) {
      errors.push(`${label}: ${path.relative(ROOT, compPath)} already exists (use --force). 블록 유지.`);
      continue;
    }
    if (!args.dry) {
      await mkdir(compDir, { recursive: true });
      await writeFile(compPath, renderComponentSource(name, spec), "utf8");
    }
    createdComponents.push(path.relative(ROOT, compPath));
    newImports.push(`import ${name} from "../../components/posts/${slug}/${name}";`);
    replacements.push({ from: m[0], to: `<${name} />` });
  }

  // apply block replacements
  for (const r of replacements) body = body.replace(r.from, r.to);

  // insert new imports (dedup against whole file)
  const importsToAdd = newImports.filter((l) => !content.includes(l));
  let result = frontmatter;
  if (importsToAdd.length) result += importsToAdd.join("\n") + "\n\n";
  result += body.replace(/^\n+/, ""); // trim leading blank lines from body

  if (!args.dry) await writeFile(filePath, result, "utf8");

  // report
  console.log(`[apply-viz] ${args.file} (slug=${slug})${args.dry ? " [dry]" : ""}`);
  for (const c of createdComponents) console.log(`  + component  ${c}`);
  for (const h of heroCreated) console.log(`  + hero webp  ${h}`);
  for (const i of importsToAdd) console.log(`  + import     ${i}`);
  console.log(
    `  replaced ${replacements.length} block(s) (${heroCount} hero), created ${createdComponents.length} component(s)`,
  );
  if (errors.length) {
    console.log(`  ⚠ ${errors.length} issue(s):`);
    for (const e of errors) console.log(`    - ${e}`);
  }
  if (errors.length) process.exitCode = 2;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
