#!/usr/bin/env bun
/**
 * gen-motion-css — src/styles/motion.css 생성기 (viz.css 선례 미러).
 *
 * 블로그는 콘텐츠 무JS를 유지하려고 패키지의 클라이언트-주입 CSS를 빌드타임에
 * 정적 파일로 방출한다. 이 스크립트는 세 조각을 합쳐 src/styles/motion.css를 쓴다:
 *
 *   1. :root { --bbangto-motion-* }  ← foundationToCSSString(bbangtoTonyFoundation)의
 *      motion 슬라이스만. bbangtoTonyStyleGuide.ts가 단일 진실원(subtle 예산).
 *   2. MOTION_CSS                     ← core의 @keyframes 라이브러리(bbangto-slide-in 등).
 *   3. 리빌 계약 CSS                   ← 우리 것. data-reveal 진입 애니 + Squiggle draw-on.
 *
 * astro build는 이 파일만 소비한다(패키지 런타임 주입에 의존하지 않음).
 * **결정론적**이므로 Phase D의 drift 가드 대상:
 *   bun run gen:motion && git diff --exit-code src/styles/motion.css
 *
 * 사용: bun scripts/gen-motion-css.ts   (또는 bun run gen:motion)
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { MOTION_CSS } from "@centurio1987/bbangto-ui-core";
import { foundationToCSSString } from "@centurio1987/bbangto-ui-tokens";
import { bbangtoTonyFoundation } from "../src/lib/motion/bbangtoTonyStyleGuide";

const ROOT = process.cwd();
const OUT = path.join(ROOT, "src", "styles", "motion.css");

/** 설치된 패키지 버전(KEEP IN SYNC 헤더용). 버전이 바뀌면 drift 가드가 잡는다. */
function pkgVersion(name: string): string {
  const p = path.join(ROOT, "node_modules", name, "package.json");
  return JSON.parse(readFileSync(p, "utf8")).version as string;
}

const CORE_V = pkgVersion("@centurio1987/bbangto-ui-core");
const TOKENS_V = pkgVersion("@centurio1987/bbangto-ui-tokens");
const CATALOG_V = pkgVersion("@centurio1987/bbangto-ui-style-guide-catalog");

/** foundationToCSSString 전체에서 --bbangto-motion-* 선언만 추린다. */
function motionVars(): string {
  return foundationToCSSString(bbangtoTonyFoundation)
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.startsWith("--bbangto-motion-"))
    .map((l) => "  " + l)
    .join("\n");
}

/**
 * 리빌 계약 — 콘텐츠 무JS/reduced-motion 안전.
 *  - 숨김(opacity:0)은 html.reveal-ready 뒤에만 건다 → JS 미실행/실패 시 항상 보임.
 *  - reduced-motion 사용자는 reveal.ts가 reveal-ready를 안 붙인다(항상 보임) + 전역
 *    @media reduced 차단 규칙(global.css)이 애니를 죽인다.
 *  - 개별 애니 = duration-slow(240ms) ≤ 0.25s(원칙 #5). 스태거 delay는 cap 4로 상한.
 */
const REVEAL_CONTRACT = `
/* --- 리빌 계약 (blog-owned) ------------------------------------------------
 * data-reveal 요소는 공유 IntersectionObserver(src/lib/motion/reveal.ts)가
 * data-reveal-visible 을 세팅하면 진입 애니를 재생한다. Reveal.astro 가 래퍼.
 * dir ∈ up(기본)·down·left·right·none·draw. 스태거는 style="--reveal-i:N".            */

/* 진입 방향별 slide 오프셋(무JS에서도 무해 — 애니가 없으면 그냥 변수일 뿐). */
[data-reveal] { --bbangto-slide-x: 0; --bbangto-slide-y: 12px; } /* = up(기본) */
[data-reveal="down"] { --bbangto-slide-x: 0; --bbangto-slide-y: -12px; }
[data-reveal="left"] { --bbangto-slide-x: 12px; --bbangto-slide-y: 0; }
[data-reveal="right"] { --bbangto-slide-x: -12px; --bbangto-slide-y: 0; }
[data-reveal="none"] { --bbangto-slide-x: 0; --bbangto-slide-y: 0; }

/* --- slide/fade 변형 (draw 제외) --- */
/* 숨김은 reveal-ready 뒤에서만(스크립트 성공 신호). */
html.reveal-ready [data-reveal]:not([data-reveal="draw"]) { opacity: 0; }

/* 진입: slide-in(페이드+이동). backwards fill → 애니 종료 후 transform 이 원복돼
 * 요소 고유 :hover transform(예: 카드 lift, .post-row translateX)이 보존된다.
 * opacity 는 규칙이 1로 유지, delay 동안엔 backwards 로 from(opacity:0) 을 표시.
 * 스태거 delay cap = min(i,4)*40ms (원칙 #5 ≤0.25s 취지 보전). */
html.reveal-ready [data-reveal]:not([data-reveal="draw"])[data-reveal-visible] {
  opacity: 1;
  animation: bbangto-slide-in var(--bbangto-motion-duration-slow)
    var(--bbangto-motion-easing-out) backwards;
  animation-delay: calc(min(var(--reveal-i, 0), 4) * 40ms);
}

/* --- draw 변형 (Squiggle 구분선): opacity 는 요소 고유값 유지, dashoffset 으로만 감춤 --- */
html.reveal-ready [data-reveal="draw"] {
  stroke-dasharray: var(--draw-len, 600);
  stroke-dashoffset: var(--draw-len, 600);
}
html.reveal-ready [data-reveal="draw"][data-reveal-visible] {
  animation: bbangto-draw-on var(--bbangto-motion-duration-slow)
    var(--bbangto-motion-easing-out) forwards;
}
@keyframes bbangto-draw-on {
  to { stroke-dashoffset: 0; }
}
`;

const header = `/*
 * motion.css — AUTO-GENERATED. DO NOT EDIT BY HAND.
 * ---------------------------------------------------------------------------
 * Generated by: scripts/gen-motion-css.ts   (bun run gen:motion)
 * SOURCE OF TRUTH: src/lib/motion/bbangtoTonyStyleGuide.ts (bbangtoTonyFoundation).
 *
 * Composed from:
 *   - @centurio1987/bbangto-ui-core@${CORE_V}                 (MOTION_CSS @keyframes)
 *   - @centurio1987/bbangto-ui-tokens@${TOKENS_V}               (foundationToCSSString)
 *   - @centurio1987/bbangto-ui-style-guide-catalog@${CATALOG_V}  (makeSemantic/makeFoundations)
 *
 * WHY a generated file: the blog keeps content zero-JS (viz.css 선례). The core
 * motion layer normally injects its stylesheet at runtime; we emit it statically
 * so scroll-reveal + page motion paint at build time without hydration.
 *
 * KEEP IN SYNC: this file is DETERMINISTIC given the package versions above.
 * If you bump a package or edit bbangtoTonyStyleGuide.ts, re-run \`bun run gen:motion\`
 * and commit. CI (Phase D) guards drift with:
 *   bun run gen:motion && git diff --exit-code src/styles/motion.css
 */`;

/**
 * KAN-059 — 첫 화면 그림이 폰트보다 먼저 도착하게 만들면서 들어온 계약.
 *
 * **이 블록이 처음엔 생성물(`src/styles/motion.css`)에 손으로 붙어 있었다.** 생성기가
 * 그것을 모르니 `gen:motion` 이 매번 지웠고, CI 의 드리프트 가드가 그것을 잡아
 * **2026-07-31 부터 빌드가 33회 연속 실패했다** — build → deploy 가 한 잡이라 그동안
 * 사이트가 한 번도 배포되지 않았다. 생성물에 손을 대면 조용히 되돌아간다는 규칙이
 * 실제로 어떻게 무는지를 보여 준 자리다. 그래서 여기로 옮겼다(2026-08-25).
 *
 * 내용은 옮기기 전과 한 글자도 다르지 않다 — 템플릿 리터럴이라 백틱만 이스케이프했다.
 */
const IMGWAIT_CONTRACT = `
/* --- 이미지 도착 대기 계약 (blog-owned, KAN-059) ---------------------------
 * \`[data-imgwait]\` 는 **그림이 도착할 때까지 자리를 비워 두는** 표식이다.
 * BaseLayout.astro 의 \`is:inline\` 스크립트(arm)가 준비되면 data-imgready 를 세팅한다.
 *
 * 왜 개별 이미지 페이드가 아니라 "판 단위 대기"인가 —
 * 홈 히어로에서 늦게 뜨는 건 그림 한 장이 아니라 **구도**였다. 말풍선·테이프·반짝·
 * 이름표는 CSS/SVG 라 즉시 그려지는데 주인공(마스코트 래스터)만 늦어서, 데코가 빈
 * 모눈종이를 가리키며 말을 거는 화면이 몇 백 ms 씩 떴다(실측 스크린샷). 그래서
 * 마스코트가 준비될 때까지 **판 전체**를 비워 두고 한 번에 들여보낸다.
 *
 * 안전 원칙은 리빌 계약과 같다(콘텐츠는 절대 못 숨긴다):
 *  - 숨김은 <html class="reveal-ready"> 뒤에서만 산다. 무JS·reduced-motion·IO 미지원이면
 *    클래스가 없어 **지금과 똑같이** 즉시 보인다.
 *  - arm 에 상한 타임아웃(3s)이 있어 그림이 영영 안 와도(404·오프라인) 반드시 보인다.
 *  - 대기 대상은 판이지 텍스트가 아니다 — 히어로 제목·CTA 는 그대로 먼저 뜬다.
 *  - ⚠ **표시하는 쪽은 reveal-ready 를 조건으로 삼지 않는다.** 숨기는 건 이 클래스지만,
 *    표시까지 여기 걸면 View Transitions 와 경합한다: 스왑이 <html> 의 class 를 새 문서
 *    것으로 갈아치워 page-load 시점엔 클래스가 없고 그 직후에 다시 붙는데, 그 틈에
 *    "숨기는 게 없으니 할 일도 없다"며 빠져나가면 표시할 사람이 사라져 사진이 영영
 *    opacity 0 으로 굳는다(상한 타임아웃도 등록 전이라 안 걸린다). 한 번 겪은 회귀이고
 *    실측 트레이스는 BaseLayout 의 arm 주석에 있다. reveal.ts 가 같은 자리에서
 *    reveal-ready 를 **스스로 붙이고 진행**하는 것이 이 계약의 올바른 모양이다.        */
html.reveal-ready [data-imgwait] { opacity: 0; }
html.reveal-ready [data-imgwait][data-imgready] {
  opacity: 1;
  transition: opacity var(--bbangto-motion-duration-slow)
    var(--bbangto-motion-easing-out);
}
`;

const out = [
  header,
  "",
  "/* --- 1) 모션 토큰 (bbangtoTonyFoundation, subtle 예산) --------------------- */",
  ":root {",
  motionVars(),
  "}",
  "",
  `/* --- 2) MOTION_CSS — core @keyframes 라이브러리 (bbangto-ui-core@${CORE_V}) ---- */`,
  MOTION_CSS.trim(),
  "",
  REVEAL_CONTRACT.trim(),
  "",
  IMGWAIT_CONTRACT.trim(),
  "",
].join("\n");

writeFileSync(OUT, out, "utf8");
console.log(
  `[gen-motion-css] wrote ${path.relative(ROOT, OUT)} ` +
    `(core@${CORE_V} · tokens@${TOKENS_V} · catalog@${CATALOG_V}, ${out.length} bytes)`,
);
