// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Comparison } from "@centurio1987/bbangto-ui-visualization";

export default function VizComparison3() {
  return (
    <VizFigure caption={"1.24 전후 — 무엇이 사라졌나"}>
      <Comparison
        accessible="img"
        title={"dockershim 시절과 제거 이후의 호출 경로 비교"}
        desc={"1.24 전후 — 무엇이 사라졌나"}
        viewBox="0 0 600 200"
        mode="split"
        data={{
  "left": {
    "label": "1.24 이전",
    "items": [
      "kubelet → dockershim → dockerd",
      "어댑터가 k8s 저장소 안에",
      "특정 벤더 전용 코드 유지"
    ]
  },
  "right": {
    "label": "1.24 이후",
    "items": [
      "kubelet → containerd",
      "CRI 플러그인 내장",
      "중간 한 겹이 사라짐"
    ]
  }
}}
      />
    </VizFigure>
  );
}
