// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { Flowchart } from "@centurio1987/bbangto-ui-visualization";

export default function VizFlowchart4() {
  return (
    <VizFigure caption={"세 편이 만나는 자리 — 위는 CRI, 아래는 OCI"}>
      <Flowchart
        accessible="img"
        title={"kubelet에서 CRI를 거쳐 containerd, shim, runc로 이어지는 계층 구조"}
        desc={"세 편이 만나는 자리 — 위는 CRI, 아래는 OCI"}
        viewBox="0 0 600 420"
        data={{
  "nodes": [
    {
      "id": "kubelet",
      "x": 110,
      "y": 14,
      "width": 380,
      "height": 50,
      "label": "kubelet — CRI 클라이언트"
    },
    {
      "id": "cri",
      "x": 110,
      "y": 100,
      "width": 380,
      "height": 50,
      "label": "containerd / CRI-O — CRI 서버"
    },
    {
      "id": "shim",
      "x": 110,
      "y": 186,
      "width": 380,
      "height": 50,
      "label": "shim — 파드 단위로 묶인다 (EP1)"
    },
    {
      "id": "runc",
      "x": 110,
      "y": 272,
      "width": 380,
      "height": 50,
      "label": "runc — OCI 번들을 실행 (EP2)"
    },
    {
      "id": "kernel",
      "x": 110,
      "y": 358,
      "width": 380,
      "height": 44,
      "label": "커널 — namespace · cgroup"
    }
  ],
  "edges": [
    {
      "id": "e1",
      "from": "kubelet",
      "to": "cri",
      "routing": "straight"
    },
    {
      "id": "e2",
      "from": "cri",
      "to": "shim",
      "routing": "straight"
    },
    {
      "id": "e3",
      "from": "shim",
      "to": "runc",
      "routing": "straight"
    },
    {
      "id": "e4",
      "from": "runc",
      "to": "kernel",
      "routing": "straight"
    }
  ]
}}
      />
    </VizFigure>
  );
}
