// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import { ProcessSteps } from "@centurio1987/bbangto-ui-visualization";

export default function VizProcessSteps2() {
  return (
    <VizFigure caption={"파드 하나가 뜨는 순서 — 껍데기가 먼저다"}>
      <ProcessSteps
        accessible="img"
        title={"RunPodSandbox에서 시작해 PullImage, CreateContainer, StartContainer로 이어지는 CRI 호출 순서"}
        desc={"파드 하나가 뜨는 순서 — 껍데기가 먼저다"}
        viewBox="0 0 600 260"
        orientation="vertical"
        data={{
  "steps": [
    {
      "title": "RunPodSandbox",
      "description": "파드 껍데기와 네트워크를 만든다"
    },
    {
      "title": "PullImage",
      "description": "필요한 이미지를 받는다"
    },
    {
      "title": "CreateContainer",
      "description": "그 샌드박스 안에 컨테이너를 만든다"
    },
    {
      "title": "StartContainer",
      "description": "컨테이너를 시작한다"
    }
  ]
}}
      />
    </VizFigure>
  );
}
