// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import Comparison from "../../../lib/viz/Comparison";

export default function AdoptionCriteria() {
  return (
    <VizFigure caption={"새 도구를 실 작업 환경까지 들일지 가르는 두 기준"}>
      <Comparison
        accessible="img"
        title={"업무 효율 향상과 패러다임 얼터링을 두 열로 비교한 그림"}
        desc={"새 도구를 실 작업 환경까지 들일지 가르는 두 기준"}
        viewBox="0 0 600 260"
        mode="split"
        data={{
  "left": {
    "label": "업무 효율 향상",
    "items": [
      "작업 동선은 그대로 두고 그 위를 빠르게 만든다",
      "동선을 개선시켜 줄 확실한 실마리가 보여야 한다",
      "실마리가 없으면 샌드박스에 남겨 둔다"
    ]
  },
  "right": {
    "label": "패러다임 얼터링",
    "items": [
      "작업 동선 자체가 다른 모양으로 바뀐다",
      "바꿔버릴 만한 가치가 있으면 적응 비용을 낸다",
      "그때만 실 작업 환경으로 들인다"
    ]
  }
}}
      />
    </VizFigure>
  );
}
