// AUTO-GENERATED by scripts/apply-viz.ts from a ```viz``` block.
// Edit the source block in the post and re-run apply-viz to regenerate.
import VizFigure from "../../viz/VizFigure";
import Comparison from "../../../lib/viz/Comparison";

export default function WindowFootprint() {
  return (
    <VizFigure caption={"창 구성이 접힌 자리"}>
      <Comparison
        accessible="img"
        title={"이전 작업 환경의 창 구성과 orca로 옮긴 뒤의 창 구성을 두 열로 비교한 그림"}
        desc={"창 구성이 접힌 자리"}
        viewBox="0 0 600 240"
        mode="split"
        data={{
  "left": {
    "label": "옮기기 전",
    "items": [
      "vscode 창 여러 개",
      "obsidian 창 여러 개",
      "cmux 창 하나",
      "브라우저"
    ]
  },
  "right": {
    "label": "옮긴 뒤",
    "items": [
      "orca 창 하나",
      "aside 창 하나",
      "claude design"
    ]
  }
}}
      />
    </VizFigure>
  );
}
